[package]
name = "sysprocalc"
version = "1.0.0"
authors = ["Ramshankar <v.ramshankar@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Teknomancer/sysprocalc"

description = "System Programmer's Calculator"
keywords = ["x86","expression","evaluator"]
readme = "README.md"

edition = "2018"

[workspace]

[dependencies]
spceval = { path = "spceval" }
log = "0.4"

