# Run using: cargo +nightly fmt --all
edition = "2024"
style_edition = "2024" # see https://doc.rust-lang.org/edition-guide/rust-2024/rustfmt-formatting-fixes.html
max_width = 120
comment_width = 120
use_small_heuristics = "Max"
hex_literal_case = "Lower"
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50
