[package]
name = "spceval"
version = "1.0.0"
authors = ["Ramshankar <v.ramshankar@gmail.com>"]

description = "System Programmer's Calculator - Evaluator Library"
keywords = ["x86","expression","evaluator"]

#repository = "https://github.com/ FILL IN THE URL later"
license = "GPL-3.0"
edition = "2018"

[dependencies]
log = "0.4"

