name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup update stable
    - name: Build_Windows
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --all --verbose
  
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup update stable
    - name: Build_Linux
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --all --verbose

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup update stable
    - name: Build_MacOS
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --all --verbose
