name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build_Win
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --all --verbose
  build-win:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build_Lnx
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --all --verbose
